function ConvertTo-HMTScript {
    param(
        [System.Collections.Specialized.OrderedDictionary] $cfg
    )

    $script = "# This script is automatically generated by HMT`n"
    $hmt_options = $hmt._
    $stages = keys $hmt '_'
    foreach( $stage in $stages) {
         $s = Convert-Stage2Script $stage $hmt.$stage
         $script += "`n" + $s
    }

    $script | Set-Content $PSScriptRoot\..\hmt-script.ps1
}

function Convert-Stage2Script {
    param(
        [string] $StageName,
        [System.Collections.Specialized.OrderedDictionary] $StageData
    )
    Write-Verbose "Converting stage $StageName to script"

    $options = $StageData.stage

    $stage   = "stage '$StageName' {"
    $runners = keys $StageData 'stage'
    $script  = ''
    foreach ( $r in $runners ) {
        $rdef, $opts = Get-RunnerDefinition $r
        $params, $pre = Get-RunnerParams $StageData.$r $opts
        if ($pre) {$script += $pre }
        $script += "{0} {1}`n`n" -f $rdef, $params 
    }
    $script
}

function titlecase($a) {
    (Get-Culture).TextInfo.ToTitleCase($a)
}

function to_yaml_param($name, $val) {
    $pname = "`$p_${name}"
    $pval  = "${pname} = ConvertFrom-Yaml @""`n" 
    $pval += Expand-PoshString (ConvertTo-Yaml $val)
    $pval += """@`n"
    $pname, $pval
}

function Get-RunnerParams($data, $opts) {
    $res = $pre = ''

    if ($opts.Contains('s')) {
        $data | % { $res += ' -' + (titlecase $_).Replace(' ','') }
    } else { 
        if ($data -is [System.Collections.Specialized.OrderedDictionary]) {
            $data.Keys | % { 
                $val = $data.$_
                if ($val -is [string]) { $val = Expand-PoshString $val }
                elseif ( $val.GetType().BaseType.Name -ne 'ValueType' ) {
                    $val, $p = to_yaml_param $_ $val
                    $pre += $p
                }

                $res += ' -{0} {1}' -f (titlecase $_), $val
            } 
        }
        if ($data -is [string]) { $res = "'$data'" }
        if ($data.GetType().Name -eq 'List`1') {
            for($i = 0; $i -lt $data.Count; $i++){
                $val = $data[ $i ]
                if ($val -is [string]) { $val = Expand-PoshString $val }
                else {
                    $val, $p = to_yaml_param $i $val
                    $pre += $p
                }
                $res += $val
            }

        }
    }
    if ($opts.Contains('f')) { $res += ' -Force' }

    $res.Trim(), $pre
}

function Get-RunnerDefinition( $Name )
{
    # if ($Name.EndsWith(':')) { 
    #     $Name = $Name.Substring(0, $Name.Length-2)
    #     $explicit = $true
    # } 

    if (($Name -match '(?<=\|).+') -or ($Name -match '\$$')) {
        $o = $Matches[0].Trim()

        $Name = $Name -replace '\s*\|.+'
    } else { $o = '' }

    if ($o -eq '$') { $Name = 'iex'}
    $n = gcm $Name -ea 0
    if (!$n) { 
        $n = $Name.Replace(' ', '-')
        $n = gcm $n -ea 0
        if (!$n) { throw "Can't find command: $Name" }
    }
    if ($n.CommandType -eq 'Alias') { $n = $n.Definition }
    return $n,$o
}

function keys( $hash, $exclude ) { $hash.Keys | ? { $exclude -notcontains $_ } }